server:
    port: 9997

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joseniquen/ConfigServer
          searchPaths: config-data-main
          default-label: main
          username: josecarlosniquenalvarado@gmail.com
          password: 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
